[mypy]
python_version = 3.14
plugins = mypy_django_plugin.main, mypy_drf_plugin.main
strict = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
warn_unreachable = True
ignore_missing_imports = False

[mypy.plugins.django-stubs]
django_settings_module = "config.settings"

[mypy-core.infrastructure.grpc.generated.*]
ignore_errors = True

[mypy-pricing.*]
ignore_missing_imports = True

[mypy-fulfillment.*]
ignore_missing_imports = True

[mypy-common.*]
ignore_missing_imports = True

[mypy-fleet.*]
ignore_missing_imports = True

[mypy-returns.*]
ignore_missing_imports = True
