# Generated by Django 6.1 on 2026-09-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ordermodel_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='merchant_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
